from pathlib import Path
import re
import sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()

# SettingsPage.xaml: anchor restaurant editor panels to right
p=root/'Pages/SettingsPage.xaml'
s=p.read_text(encoding='utf-8-sig')
s=s.replace('<StackPanel x:Name="CouriersPanel" Spacing="8"/>','<StackPanel x:Name="CouriersPanel" Spacing="8" HorizontalAlignment="Stretch"/>')
s=s.replace('<StackPanel x:Name="DiningAreasPanel" Spacing="8"/>','<StackPanel x:Name="DiningAreasPanel" Spacing="8" HorizontalAlignment="Stretch"/>')
p.write_text(s,encoding='utf-8-sig')

# SettingsPage.xaml.cs: Area row physically right + courier Active toggle
p=root/'Pages/SettingsPage.xaml.cs'
s=p.read_text(encoding='utf-8-sig')
s=s.replace('''    private sealed class CourierRow\n    {\n        public string Id { get; init; } = Guid.NewGuid().ToString("N");\n        public required Grid Root { get; init; }\n        public required TextBox Name { get; init; }\n        public required TextBox Phone { get; init; }\n    }''','''    private sealed class CourierRow\n    {\n        public string Id { get; init; } = Guid.NewGuid().ToString("N");\n        public required Grid Root { get; init; }\n        public required TextBox Name { get; init; }\n        public required TextBox Phone { get; init; }\n        public required ToggleSwitch Active { get; init; }\n    }''')
old='''    private void AddAreaRow(DiningAreaOption area)\n    {\n        var grid = new Grid { ColumnSpacing = 8, FlowDirection = FlowDirection.RightToLeft, HorizontalAlignment = HorizontalAlignment.Stretch };\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(170) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });\n        var defaultName = string.IsNullOrWhiteSpace(area.Name) ? $"صالة {_areaRows.Count + 1}" : area.Name.Trim();\n        var name = new TextBox { Header = "اسم الصالة", Text = defaultName, HorizontalAlignment = HorizontalAlignment.Stretch, FlowDirection = FlowDirection.RightToLeft, TextAlignment = TextAlignment.Right };\n        var count = new NumberBox { Header = "عدد الترابيزات", Value = Math.Max(1, area.TableCount), Minimum = 1, Maximum = 200, SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Compact, HorizontalAlignment = HorizontalAlignment.Stretch };\n        var remove = new Button { Content = "حذف", Style = (Style)Application.Current.Resources["DangerButtonStyle"], VerticalAlignment = VerticalAlignment.Bottom };\n        Grid.SetColumn(name, 0); Grid.SetColumn(count, 1); Grid.SetColumn(remove, 2);\n        grid.Children.Add(name); grid.Children.Add(count); grid.Children.Add(remove);\n        var row = new AreaRow { Id = string.IsNullOrWhiteSpace(area.Id) ? Guid.NewGuid().ToString("N") : area.Id, Root = grid, Name = name, Count = count };\n        remove.Click += (_, _) => { _areaRows.Remove(row); DiningAreasPanel.Children.Remove(grid); RenumberBlankAreas(); };\n        _areaRows.Add(row); DiningAreasPanel.Children.Add(grid);\n    }'''
new='''    private void AddAreaRow(DiningAreaOption area)\n    {\n        // Keep hall rows physically anchored to the right directly under \"الصالات والترابيزات\".\n        var grid = new Grid { Width = 680, MaxWidth = 680, ColumnSpacing = 8, FlowDirection = FlowDirection.RightToLeft, HorizontalAlignment = HorizontalAlignment.Right };\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(360) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(170) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });\n        var defaultName = string.IsNullOrWhiteSpace(area.Name) ? $"صالة {_areaRows.Count + 1}" : area.Name.Trim();\n        var name = new TextBox { Header = "اسم الصالة", Text = defaultName, Width = 360, HorizontalAlignment = HorizontalAlignment.Right, FlowDirection = FlowDirection.RightToLeft, TextAlignment = TextAlignment.Right };\n        var count = new NumberBox { Header = "عدد الترابيزات", Value = Math.Max(1, area.TableCount), Minimum = 1, Maximum = 200, SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Compact, Width = 170, HorizontalAlignment = HorizontalAlignment.Right };\n        var remove = new Button { Content = "حذف", Style = (Style)Application.Current.Resources["DangerButtonStyle"], VerticalAlignment = VerticalAlignment.Bottom, HorizontalAlignment = HorizontalAlignment.Right };\n        Grid.SetColumn(name, 0); Grid.SetColumn(count, 1); Grid.SetColumn(remove, 2);\n        grid.Children.Add(name); grid.Children.Add(count); grid.Children.Add(remove);\n        var row = new AreaRow { Id = string.IsNullOrWhiteSpace(area.Id) ? Guid.NewGuid().ToString("N") : area.Id, Root = grid, Name = name, Count = count };\n        remove.Click += (_, _) => { _areaRows.Remove(row); DiningAreasPanel.Children.Remove(grid); RenumberBlankAreas(); };\n        _areaRows.Add(row); DiningAreasPanel.Children.Add(grid);\n    }'''
if old not in s: raise SystemExit('AddAreaRow block not found')
s=s.replace(old,new)
old='''    private void AddCourierRow(CourierOption courier)\n    {\n        var grid = new Grid { ColumnSpacing = 8, FlowDirection = FlowDirection.RightToLeft, HorizontalAlignment = HorizontalAlignment.Stretch };\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(220) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });\n        var name = new TextBox { Header = "اسم الطيار", Text = string.IsNullOrWhiteSpace(courier.Name) ? $"طيار {_courierRows.Count + 1}" : courier.Name, HorizontalAlignment = HorizontalAlignment.Stretch, FlowDirection = FlowDirection.RightToLeft, TextAlignment = TextAlignment.Right };\n        var phone = new TextBox { Header = "رقم الموبايل", Text = courier.Phone ?? "", HorizontalAlignment = HorizontalAlignment.Stretch, FlowDirection = FlowDirection.LeftToRight, TextAlignment = TextAlignment.Right };\n        var remove = new Button { Content = "حذف", Style = (Style)Application.Current.Resources["DangerButtonStyle"], VerticalAlignment = VerticalAlignment.Bottom };\n        Grid.SetColumn(name, 0); Grid.SetColumn(phone, 1); Grid.SetColumn(remove, 2);\n        grid.Children.Add(name); grid.Children.Add(phone); grid.Children.Add(remove);\n        var row = new CourierRow { Id = string.IsNullOrWhiteSpace(courier.Id) ? Guid.NewGuid().ToString("N") : courier.Id, Root = grid, Name = name, Phone = phone };\n        remove.Click += (_, _) => { _courierRows.Remove(row); CouriersPanel.Children.Remove(grid); };\n        _courierRows.Add(row); CouriersPanel.Children.Add(grid);\n    }'''
new='''    private void AddCourierRow(CourierOption courier)\n    {\n        var grid = new Grid { ColumnSpacing = 8, FlowDirection = FlowDirection.RightToLeft, HorizontalAlignment = HorizontalAlignment.Stretch };\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(220) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(110) });\n        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });\n        var name = new TextBox { Header = "اسم الطيار", Text = string.IsNullOrWhiteSpace(courier.Name) ? $"طيار {_courierRows.Count + 1}" : courier.Name, HorizontalAlignment = HorizontalAlignment.Stretch, FlowDirection = FlowDirection.RightToLeft, TextAlignment = TextAlignment.Right };\n        var phone = new TextBox { Header = "رقم الموبايل", Text = courier.Phone ?? "", HorizontalAlignment = HorizontalAlignment.Stretch, FlowDirection = FlowDirection.LeftToRight, TextAlignment = TextAlignment.Right };\n        var active = new ToggleSwitch { Header = "الحالة", OnContent = "نشط", OffContent = "غير نشط", IsOn = courier.IsActive, VerticalAlignment = VerticalAlignment.Bottom };\n        var remove = new Button { Content = "حذف", Style = (Style)Application.Current.Resources["DangerButtonStyle"], VerticalAlignment = VerticalAlignment.Bottom };\n        Grid.SetColumn(name, 0); Grid.SetColumn(phone, 1); Grid.SetColumn(active, 2); Grid.SetColumn(remove, 3);\n        grid.Children.Add(name); grid.Children.Add(phone); grid.Children.Add(active); grid.Children.Add(remove);\n        var row = new CourierRow { Id = string.IsNullOrWhiteSpace(courier.Id) ? Guid.NewGuid().ToString("N") : courier.Id, Root = grid, Name = name, Phone = phone, Active = active };\n        remove.Click += (_, _) => { _courierRows.Remove(row); CouriersPanel.Children.Remove(grid); };\n        _courierRows.Add(row); CouriersPanel.Children.Add(grid);\n    }'''
if old not in s: raise SystemExit('AddCourierRow block not found')
s=s.replace(old,new)
s=s.replace('var couriers = _courierRows.Select((x, i) => new CourierOption { Id = x.Id, Name = string.IsNullOrWhiteSpace(x.Name.Text) ? $"طيار {i + 1}" : x.Name.Text.Trim(), Phone = x.Phone.Text.Trim(), IsActive = true }).ToList();', 'var couriers = _courierRows.Select((x, i) => new CourierOption { Id = x.Id, Name = string.IsNullOrWhiteSpace(x.Name.Text) ? $"طيار {i + 1}" : x.Name.Text.Trim(), Phone = x.Phone.Text.Trim(), IsActive = x.Active.IsOn }).ToList();')
p.write_text(s,encoding='utf-8-sig')

# Core enum + entity return info
p=root/'Core/Enums.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('public enum RestaurantOrderStatus { Open = 1, Paid = 2, Cancelled = 3, OutForDelivery = 4 }','public enum RestaurantOrderStatus { Open = 1, Paid = 2, Cancelled = 3, OutForDelivery = 4, DeliveryReturned = 5 }')
p.write_text(s,encoding='utf-8-sig')

p=root/'Core/Entities.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('''    public DateTime? DispatchedAt { get; set; }\n    public DateTime? SettledAt { get; set; }\n    public DateTime CreatedAt { get; set; }''','''    public DateTime? DispatchedAt { get; set; }\n    public DateTime? SettledAt { get; set; }\n    public DateTime? ReturnedAt { get; set; }\n    [MaxLength(500)] public string? ReturnReason { get; set; }\n    public DateTime CreatedAt { get; set; }''')
p.write_text(s,encoding='utf-8-sig')

# Database schema upgrade
p=root/'Data/DatabaseService.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('''            DispatchedAt TEXT NULL,\n            SettledAt TEXT NULL,\n            CreatedAt TEXT NOT NULL,''','''            DispatchedAt TEXT NULL,\n            SettledAt TEXT NULL,\n            ReturnedAt TEXT NULL,\n            ReturnReason TEXT NULL,\n            CreatedAt TEXT NOT NULL,''')
s=s.replace('''        if (!await HasColumnAsync("RestaurantOrders", "SettledAt")) await ExecAsync("ALTER TABLE RestaurantOrders ADD COLUMN SettledAt TEXT NULL;");''','''        if (!await HasColumnAsync("RestaurantOrders", "SettledAt")) await ExecAsync("ALTER TABLE RestaurantOrders ADD COLUMN SettledAt TEXT NULL;");\n        if (!await HasColumnAsync("RestaurantOrders", "ReturnedAt")) await ExecAsync("ALTER TABLE RestaurantOrders ADD COLUMN ReturnedAt TEXT NULL;");\n        if (!await HasColumnAsync("RestaurantOrders", "ReturnReason")) await ExecAsync("ALTER TABLE RestaurantOrders ADD COLUMN ReturnReason TEXT NULL;");''')
p.write_text(s,encoding='utf-8-sig')

# RestaurantService: add returned handling, leave kitchen delta calculation to receipt (already uses Quantity-SentQuantity)
p=root/'Services/RestaurantService.cs'; s=p.read_text(encoding='utf-8-sig')
needle='''    public async Task MarkPaidAsync(int orderId, int saleId)\n    {'''
insert='''    public async Task MarkDeliveryReturnedAsync(int orderId, string reason)\n    {\n        var cleanReason = (reason ?? "").Trim();\n        if (string.IsNullOrWhiteSpace(cleanReason)) throw new InvalidOperationException("اكتب سبب عدم تسليم الطلب.");\n        await using var db = database.CreateContext();\n        var order = await db.RestaurantOrders.FirstOrDefaultAsync(x => x.Id == orderId && x.OrderType == RestaurantOrderType.Delivery && x.Status == RestaurantOrderStatus.OutForDelivery)\n            ?? throw new InvalidOperationException("طلب الدليفري غير متاح للتسجيل كمرتجع.");\n        order.Status = RestaurantOrderStatus.DeliveryReturned;\n        order.ReturnReason = cleanReason;\n        order.ReturnedAt = DateTime.Now;\n        order.SettledAt = DateTime.Now;\n        order.UpdatedAt = DateTime.Now;\n        await db.SaveChangesAsync();\n        await audit.WriteAsync("DeliveryReturned", "RestaurantOrder", order.Id.ToString(), $"{order.CourierName} • {cleanReason}");\n    }\n\n'''+needle
if needle not in s: raise SystemExit('MarkPaid needle missing')
s=s.replace(needle,insert)
p.write_text(s,encoding='utf-8-sig')


print('R3 core/settings patch applied')
