-- Geek POS Online schema. Run in Supabase SQL Editor after creating your project.
create table if not exists public.pos_snapshots (
  store_id text primary key,
  app_version text,
  device_name text,
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);
create table if not exists public.pos_updates (
  id bigint generated by default as identity primary key,
  store_id text not null,
  update_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  applied_at timestamptz
);
alter table public.pos_snapshots enable row level security;
alter table public.pos_updates enable row level security;
-- Initial private-project policies. Create Supabase Auth users for the POS device and dashboard admin.
create policy "authenticated read snapshots" on public.pos_snapshots for select to authenticated using (true);
create policy "authenticated write snapshots" on public.pos_snapshots for insert to authenticated with check (true);
create policy "authenticated update snapshots" on public.pos_snapshots for update to authenticated using (true) with check (true);
create policy "authenticated read updates" on public.pos_updates for select to authenticated using (true);
create policy "authenticated create updates" on public.pos_updates for insert to authenticated with check (true);
create policy "authenticated update updates" on public.pos_updates for update to authenticated using (true) with check (true);
